#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.  
def solve(s):
  l=list(s)
  l[0]=l[0].upper()
  for i in range(len(l)):
    if l[i]==' ' and l[i+1]!=' ':
      l[i+1]=l[i+1].upper()
  l=''.join(l)
  return l
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
